import type { Product } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  {
    _id: "mock-1",
    title: "Venetian Crystal Cascade",
    slug: "venetian-crystal-cascade",
    sku: "CS-001",
    price: 3200,
    style: "Classic",
    material: "Crystal",
    room: "Dining",
    priceRange: "$2,500 – $5,000",
    dimensions: "Large (80 – 120 cm)",
    shortDescription: "Hand-cut crystal tiers with warm brass frame",
    featured: true,
    imageUrl:
      "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&q=80",
    imageAlt: "Venetian Crystal Cascade chandelier",
    publishedAt: "2025-01-15",
  },
  {
    _id: "mock-2",
    title: "Atelier Brass Orb",
    slug: "atelier-brass-orb",
    sku: "CS-002",
    price: 1850,
    style: "Modern",
    material: "Brass",
    room: "Living Room",
    priceRange: "$1,000 – $2,500",
    dimensions: "Medium (40 – 80 cm)",
    shortDescription: "Sculptural orb in brushed brass",
    featured: true,
    imageUrl:
      "https://images.unsplash.com/photo-1524484484925-d28411c5a562?w=800&q=80",
    imageAlt: "Atelier Brass Orb chandelier",
    publishedAt: "2025-02-01",
  },
  {
    _id: "mock-3",
    title: "Loft Industrial Cage",
    slug: "loft-industrial-cage",
    sku: "CS-003",
    price: 890,
    style: "Industrial",
    material: "Glass",
    room: "Living Room",
    priceRange: "$500 – $1,000",
    dimensions: "Medium (40 – 80 cm)",
    shortDescription: "Smoked glass panels in matte black cage",
    featured: false,
    imageUrl:
      "https://images.unsplash.com/photo-1565814329452-4a4d2a8b0f6b?w=800&q=80",
    imageAlt: "Loft Industrial Cage chandelier",
    publishedAt: "2025-03-10",
  },
  {
    _id: "mock-4",
    title: "Rattan Solstice",
    slug: "rattan-solstice",
    sku: "CS-004",
    price: 640,
    style: "Vintage",
    material: "Rattan",
    room: "Bedroom",
    priceRange: "$500 – $1,000",
    dimensions: "Small (under 40 cm)",
    shortDescription: "Woven rattan with diffused warm glow",
    featured: true,
    imageUrl:
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80",
    imageAlt: "Rattan Solstice pendant",
    publishedAt: "2025-04-05",
  },
  {
    _id: "mock-5",
    title: "Grand Salon Crystal",
    slug: "grand-salon-crystal",
    sku: "CS-005",
    price: 7800,
    style: "Classic",
    material: "Crystal",
    room: "Dining",
    priceRange: "Over $5,000",
    dimensions: "Extra Large (over 120 cm)",
    shortDescription: "Statement tiered crystal for formal dining",
    featured: true,
    imageUrl:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    imageAlt: "Grand Salon Crystal chandelier",
    publishedAt: "2025-05-20",
  },
  {
    _id: "mock-6",
    title: "Minimal Glass Line",
    slug: "minimal-glass-line",
    sku: "CS-006",
    price: 420,
    style: "Modern",
    material: "Glass",
    room: "Bedroom",
    priceRange: "Under $500",
    dimensions: "Small (under 40 cm)",
    shortDescription: "Linear glass rods on satin nickel",
    featured: false,
    imageUrl:
      "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80",
    imageAlt: "Minimal Glass Line fixture",
    publishedAt: "2025-06-01",
  },
];
